version: "3.9"
services:

  achat:
    image: "nesrinewer/achat-1.0"
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      -  db-mysql

  db-mysql:
    image: "mysql:5.7"
    container_name: db-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
      db: